services:
  # A Node.js web service
  - type: web
    name: nodeJsTestRender
    plan: free
    runtime: node
    repo: https://github.com/Sitron808/CloudTest
    region: frankfurt
    branch: main
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: DBCONNECTIONSTRING
        fromDatabase:
          name: nodeJsTestRender-db
          property: connectionString

databases:
  - name: nodeJsTestRender-db
    region: frankfurt
    plan: free