services:
  - type: web
    name: esgi-2i1
    runtime: node
    region: frankfurt
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: DB_CONNECTION_STRING
        fromDatabase: esgi
        property: connectionString
databases:
  - name: esgi
    region: frankfurt
